version: '3'

services:
  registry:
    container_name: registry
    restart: unless-stopped
    image: registry:2.8
    ports:
      - 5000:5000
    volumes:
      - '${PWD}/registry.config.yaml:/etc/docker/registry/config.yml:ro'
      - '${HOME}/docker-registry:/var/lib/registry:rw'
    # environment:
    #   - "STANDALONE=true"
    #   - "MIRROR_SOURCE=https://registry-1.docker.io"
    #   - "MIRROR_SOURCE_INDEX=https://index.docker.io"
