version: '3.9'

networks:
  proxy:
    name: service-proxy

services:
  minio:
    image: minio/minio
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          memory: 32M
      labels:
        - traefik.enable=true
        - traefik.http.services.minio.loadbalancer.server.port=9000
        - traefik.http.services.minio-admin.loadbalancer.server.port=9001
        # - traefik.http.routers.minio.entrypoints=web-secure
        # - traefik.http.routers.minio.service=minio@docker
        # - traefik.http.routers.minio.rule=Host(`cdn.trace.ng`)
        # - traefik.http.routers.minio-admin.entrypoints=web-insecure
        # - traefik.http.routers.minio-admin.service=minio-admin@docker
        # - traefik.http.routers.minio-admin.rule=Host(`manage.trace.ng/storage`)
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - '${STORE_ROOT}/minio:/data'
    env_file: '${PWD}/.env.minio'
    command: server --address 0.0.0.0:9000 --console-address ":9001" /data
    networks:
      - proxy
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:9000/minio/health/live']
      interval: 30s
      timeout: 20s
      retries: 5
  postgres:
    image: postgis/postgis:13-3.2-alpine
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '0.2'
          memory: 128M
        reservations:
          memory: 32M
    ports:
      - 5432:5432
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - '${STORE_ROOT}/postgres:/var/lib/postgresql/data/pgdata'
    env_file:
      - '${PWD}/.env.postgres'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}']
      interval: 10s
      timeout: 5s
      retries: 5
  redis:
    image: redis:5.0-alpine
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '0.2'
          memory: 128M
        reservations:
          memory: 32M
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - '${STORE_ROOT}/redis:/data'
    ports:
      - 6379:6379
    healthcheck:
      test: ['CMD-SHELL', 'redis-cli ping | grep PONG']
      interval: 1s
      timeout: 3s
      retries: 5
