version: '3.9'

networks:
  proxy:
    external: true
    name: service-proxy

volumes:
  pgadmin:

services:
  manager:
    image: ${REGISTRY_URL}/manager:${VERSION}
    build:
      context: .
      dockerfile: Dockerfile.manager
      args:
        VERSION: ${VERSION}
        SERVICE_NAME: manager
        SERVICE_PORT: 4680
    env_file:
      - '${PWD}/app/trace.service/.env.dev'
    volumes:
      # - '${PWD}/app/trace.service/.env.dev:/home/node/app/trace.service/dist/apps/manager/src/.env'
      - '${SRV_ROOT}/config.dev.yaml:/app/config.yaml:ro'
      - '${SRV_ROOT}/config/service.gateway.yaml:/app/service.yaml:ro'
    ports:
      - 4680:4680
    # networks:
    #   - proxy
  # pgadmin:
  #   image: dpage/pgadmin4
  #   ports:
  #     - 5435:80
  #   networks:
  #     - proxy
  #   volumes:
  #     - pgadmin:/var/lib/pgadmin
  #   env_file:
  #     - .env.pgadmin
