version: '3.9'

networks:
  proxy:
    external: true
    name: service-proxy

services:
  app.vector:
    image: ${REGISTRY_URL}/app-vector:${VERSION}
    build:
      context: .
      dockerfile: Dockerfile.client
      args:
        VERSION: '${VERSION}'
        APP_VARIANT: vector
    env_file:
      - ${PWD}/app/trace.client/.env.dev
    networks:
      - proxy
    healthcheck:
      test: ['CMD', 'service', 'nginx', 'status']
      interval: 30s
      timeout: 20s
      retries: 5
