app:
  debug: true
  name: Trace
  secret: xx-xxx-xxx-xx
  services:
    - name: gateway
      host: service.gateway
      port: 4560
    - name: identity
      host: service.identity
      port: 4561
    - name: operation
      host: service.operation
      port: 4562
    - name: integration
      host: service.integration
      port: 4564
    - name: navigation
      host: service.navigation
      port: 4565
    - name: manager
      host: service.manager
      port: 4570

database:
  postgres:
    type: postgres
    host: localhost
    port: 5432
    username: trace
    password: trace
    database: trace
    logging: true
    migrationsTableName: migrations
    migrationsTransactionMode: each
    synchronize: true
    installExtensions: true
    dropSchema: false
  mongodb:
    type: mongodb
    host: localhost
    port: 27017
    username: trace
    synchronize: true
