app:
  debug: true
  name: Trace
  secret: xx-xxx-xxx-xx
  services:
    - name: gateway
      host: service_gateway
      port: 4560
    - name: identity
      host: service_identity
      port: 4561
    - name: operation
      host: service_operation
      port: 4562
    - name: integration
      host: service_integration
      port: 4564
    - name: navigation
      host: service_navigation
      port: 4565
    - name: manager
      host: service_manager
      port: 4570

database:
  ## Core application database.
  operation:
    type: postgres
    host: localhost
    port: 5432
    username: trace
    password: trace
    database: trace
    logging: true
    migrationsTableName: migrations
    migrationsTransactionMode: each
    synchronize: true
    installExtensions: true
    dropSchema: false
  ## Shared document database for
  ## flat data with high traffic.
  document:
    type: mongodb
    host: localhost
    port: 27017
    database: mongodb;
    synchronize: true
    logging: true;
