version: '3.9'

networks:
  app:
    driver: bridge

services:
  postgres:
    image: postgis/postgis:14-3.2-alpine
    container_name: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data/pgdata
    env_file:
      - .env.docker
    networks:
      - app
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: unless-stopped
    ports:
      - 4580:80
    volumes:
      - pgadmin:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=trace@local.host
      - PGADMIN_DEFAULT_PASSWORD=trace
      - PGADMIN_LISTEN_ADDRESS=0.0.0.0
      - PGADMIN_CONFIG_CONSOLE_LOG_LEVEL=10
    networks:
      - app

  # yugabyte:
  #   container_name: yugabyte
  #   image: gpproton/yugabyte-postgis:latest
  #   restart: unless-stopped
  #   ports:
  #     - 9000:9000
  #     - 7000:7000
  #     - 5433:5433
  #     - 9042:9042
  #   volumes:
  #     - ~/docker-temp/yugabyte:/home/yugabyte/yb_data
  #   command: bin/yugabyted start --base_dir=/home/yugabyte/yb_data --daemon=false

volumes:
    postgres:
    pgadmin:
