version: '3.9'
services:
  postgres:
    image: postgis/postgis:14-3.2-alpine
    container_name: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - ~/docker-temp/postgres:/var/lib/postgresql/data/pgdata
    env_file:
      - .env.development
  # yugabyte:
  #   container_name: yugabyte
  #   image: gpproton/yugabyte-postgis:latest
  #   restart: unless-stopped
  #   ports:
  #     - 9000:9000
  #     - 7000:7000
  #     - 5433:5433
  #     - 9042:9042
  #   volumes:
  #     - ~/docker-temp/yugabyte:/home/yugabyte/yb_data
  #   command: bin/yugabyted start --base_dir=/home/yugabyte/yb_data --daemon=false
