$schema: 'https://steeltoe.io/schema/latest/schema.json'
Spring:
  Application:
    Name: service-identity
  Cloud:
    Config:
      Enabled: false
      FailFast: true
      HealthEnabled: true
      DiscoveryEnabled: true
    Kubernetes:
      Config:
        Sources:
          - {"Name":"default","Namespace":"trace"}
          - {"Name":"service-identity","Namespace":"trace"}
      Secrets:
        Sources:
          - {"Name":"default","Namespace":"trace"}
