AppSettings:
  SiteTitle: trace
  CacheDbResults: true
Logging:
  LogLevel:
    Default: Information
    Microsoft.AspNetCore: Warning
    Steeltoe: Debug
    Hangfire: Information
AllowedHosts: '*'
Kestrel:
  Certificates:
    Default:
      Path: localhost.pfx
      Password: ''
consul:
  discovery:
    register: true
    healthCheckPath: '/health'
management:
  endpoints:
    actuator:
      exposure:
        include: ['*']
  tracing:
    alwaysSample: true
    useShortTraceIds: true
    exporterEndpoint: http://localhost:9411/api/v2/spans
redis:
  client:
    host: localhost:6379,abortConnect=false

---
spring:
  config:
    activate:
      on-profile: Docker
consul:
  client:
    serviceUrl: http://consul:8500
management:
  tracing:
    exporter:
      zipkin:
        endpoint: http://zipkin:9411/api/v2/spans
redis:
  client:
    host: redis
