---
spring:
  config:
    activate:
      on-profile: Production
  Boot:
    Admin:
      Client:
        Url: http://localhost:1111
        ValidateCertificates: false
        Metadata:
          user.name: trace
          user.password: trace
AppSettings:
  SiteTitle: trace
  CacheDbResults: true
Logging:
  LogLevel:
    Default: Information
    Microsoft.AspNetCore: Warning
    Steeltoe: Debug
    Hangfire: Information
Serilog:
  IncludeScopes: false
  Enrich:
    - FromLogContext
    - WithMachineName
    - WithThreadId
  WriteTo:
    - Name: Console
    - Name: File
      Args:
        path: logs/trace.log.txt
        rollingInterval: Day
        rollOnFileSizeLimit: true
        outputTemplate: '[{Timestamp:HH:mm:ss} {Level:u3}] {SourceContext}: {Properties} {NewLine} {EventId} {Message:lj}{NewLine}{Exception}'
AllowedHosts: '*'
Kestrel:
  Certificates:
    Default:
      Path: localhost.pfx
      Password: ''
Management:
  Endpoints:
    Actuator:
      Exposure:
        Include:
          - '*'
        Exclude:
          - env
          - refresh
  Tracing:
    Exporter:
      Zipkin:
        Endpoint: http://localhost:9411/api/v2/spans
Consul:
  Host: localhost
  Port: 8500
  Discovery:
    Register: true
    HealthCheckPath: '/health'
Redis:
  Client:
    ConnectionString: localhost:6379,abortConnect=false
RabbitMq:
  Client:
    Uri: amqp://admin:secret@localhost:5672
Postgres:
  Client:
    ConnectionString: Server=localhost;Port=5432;Userid=trace;Password=trace;Database=trace
Hangfire:
  Endpoint: '/schedule'
  Username: trace
  Password: trace
