ReverseProxy:
  Routes:
    route1:
      ClusterId: service-gateway
      Match:
        Path: '{**catch-all}'
  Clusters:
    service-gateway:
      Destinations:
        main:
          Address: https://localhost:4570/
