consul:
  discovery:
    register: true
    healthCheckPath: '/health'
Logging:
  LogLevel:
    Default: Information
    Microsoft.AspNetCore: Warning
    Steeltoe: Debug
    Hangfire: Information
AllowedHosts: '*'
Kestrel:
  Certificates:
    Default:
      Path: localhost.pfx
      Password: ''
hangfire:
  endpoint: '/schedule'
  username: trace
  password: trace
