spring:
  rabbitMq:
    addresses: amqp://admin:secret@localhost
consul:
  discovery:
    register: true
    healthCheckPath: '/health'
redis: localhost:6379,abortConnect=false
hangfire:
  endpoint: '/schedule'
  username: trace
  password: trace
Logging:
  LogLevel:
    Default: Information
    Microsoft.AspNetCore: Warning
    Steeltoe: Debug
    Hangfire: Information
AllowedHosts: '*'
Kestrel:
  Certificates:
    Default:
      Path: localhost.pfx
      Password: ''
database:
  operation: Server=localhost;Port=5432;Userid=trace;Password=trace;Database=trace
  state: Server=localhost;Port=5433;Userid=trace;Password=trace;Database=trace
