version: '3.9'

networks:
  gateway:
    external: true
    name: gateway-net

x-app-instance: &app-instance
  build: &app-build
    context: .
    dockerfile: docker/Dockerfile.client
    args: &app-args
      VERSION: '${VERSION}'
  env_file:
    - ${PWD}/app/trace.client/.env.dev
  networks:
    - gateway
  healthcheck:
    test: ['CMD', 'service', 'nginx', 'status']
    interval: 30s
    timeout: 20s
    retries: 5

services:
  vector:
    <<: *app-instance
    image: ${REGISTRY_URL}/app-vector:${VERSION}
    build:
      <<: *app-build
      args:
        <<: *app-args
        APP_VARIANT: vector
