version: '3.9'

networks:
  database:
    driver: overlay
    attachable: true
    name: database-net

services:
  operation:
    image: postgis/postgis:15-3.3
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '0.1'
          memory: 128M
        reservations:
          memory: 32M
    ports:
      - 5432:5432
    networks:
      - database
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${STORE_ROOT}/postgres:/var/lib/postgresql/data/pgdata
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: trace
      POSTGRES_PASSWORD: trace
      POSTGRES_DB: trace
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}']
      interval: 10s
      timeout: 5s
      retries: 5
  cache:
    image: redis/redis-stack:6.2.6-v6
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '0.2'
          memory: 128M
        reservations:
          memory: 32M
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${STORE_ROOT}/redis:/data
    networks:
      - database
    ports:
      - 6379:6379
    healthcheck:
      test: ['CMD-SHELL', 'redis-cli ping | grep PONG']
      interval: 1s
      timeout: 3s
      retries: 5
