version: '3.9'

networks:
  gateway:
    external: true
    name: gateway-net

volumes:
  pgadmin:

services:
  manager:
    image: ${REGISTRY_URL}/manager:${VERSION}
    build:
      context: .
      dockerfile: docker/Dockerfile.manager
      args:
        VERSION: ${VERSION}
        SERVICE_NAME: manager
        SERVICE_PORT: 4680
    env_file:
      - '${PWD}/app/trace.service/.env.sample'
    volumes:
      # - '${PWD}/app/trace.service/.env.sample:/home/node/app/trace.service/dist/apps/manager/src/.env'
      - '${SRV_ROOT}/config.dev.yaml:/app/config.yaml:ro'
      - '${SRV_ROOT}/config/service.gateway.yaml:/app/service.yaml:ro'
    ports:
      - 4680:4680
    networks:
      - gateway
  # pgadmin:
  #   image: dpage/pgadmin4
  #   ports:
  #     - 5435:80
  #   networks:
  #     - proxy
  #   volumes:
  #     - pgadmin:/var/lib/pgadmin
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: 'trace@${DOMAIN}'
  #     PGADMIN_DEFAULT_PASSWORD: 'trace'
  #     PGADMIN_LISTEN_ADDRESS: '0.0.0.0'
  #     PGADMIN_CONFIG_CONSOLE_LOG_LEVEL: 10
