version: '3.9'

networks:
  storage:
    driver: overlay
    attachable: true
    name: storage-net

services:
  server:
    image: redis:5.0-alpine
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '0.2'
          memory: 128M
        reservations:
          memory: 32M
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - '/etc/timezone:/etc/timezone:ro'
      - '${STORE_ROOT}/redis:/data'
    networks:
      - storage
    ports:
      - 6379:6379
    healthcheck:
      test: ['CMD-SHELL', 'redis-cli ping | grep PONG']
      interval: 1s
      timeout: 3s
      retries: 5
