version: '3.9'

networks:
  scylla:
    driver: overlay
    attachable: true
    name: scylla-net

services:
  server:
    image: scylladb/scylla:5.1
    volumes:
      - .${STORE_ROOT}/scylla:/var/lib/scylla
    networks:
      - scylla
    ports:
      - "9042:9042"
      - "9160:9160"
