version: '3.9'

networks:
  service:
    driver: overlay
    attachable: true
    name: service-net
  gateway:
    external: true
    name: gateway-net
  database:
    external: true
    name: database-net
  storage:
    external: true
    name: storage-net

configs:
  shared:
    file: '${SRV_ROOT}/config.dev.yaml'
  gateway:
    file: '${SRV_ROOT}/config/service.gateway.yaml'

x-service-instance: &service-instance
  build: &service-build
    context: .
    dockerfile: docker/Dockerfile.service
    args: &service-args
      VERSION: '${VERSION}'
  env_file:
    - ./app/trace.service/.env.dev

services:
  gateway:
    <<: *service-instance
    image: '${REGISTRY_URL}/service-gateway:${VERSION}'
    build:
      <<: *service-build
      args:
        <<: *service-args
        SERVICE_NAME: gateway
        SERVICE_PORT: 4560
    configs:
      - source: shared
        target: '/app/config.yaml'
      - source: gateway
        target: '/app/service.yaml'
    networks:
      - service
      - gateway
    deploy:
      labels:
        - 'traefik.enable=true'
        - 'traefik.http.middlewares.srv-gateway-prefix.stripprefix.prefixes=/graphql'
        - 'traefik.http.services.srv-gateway.loadbalancer.server.port=4560'
        - 'traefik.http.routers.srv-gateway.entrypoints=web-secure'
        - 'traefik.http.routers.srv-gateway.rule=Host(`staging.${DOMAIN}`) && PathPrefix(`/graphql`)'
        - 'traefik.http.routers.srv-gateway.middlewares=srv-gateway-prefix'
