---
spring:
  config:
    activate:
      on-profile: Production

  Boot:
    Admin:
      Client:
        Url: http://localhost:1111
        ValidateCertificates: false
        Metadata:
          user.name: trace
          user.password: trace
AppSettings:
  SiteTitle: Trace
  CacheDbResults: true
Logging:
  LogLevel:
    Default: Information
    Microsoft.AspNetCore: Warning
    Steeltoe: Debug
    Hangfire: Information
Serilog:
  IncludeScopes: false
  Enrich:
    - FromLogContext
    - WithMachineName
    - WithThreadId
  WriteTo:
    - Name: Console
    - Name: File
      Args:
        path: logs/trace.log.txt
        rollingInterval: Day
        rollOnFileSizeLimit: true
        outputTemplate: '[{Timestamp:HH:mm:ss} {Level:u3}] {SourceContext}: {Properties} {NewLine} {EventId} {Message:lj}{NewLine}{Exception}'
AllowedHosts: '*'
Management:
  Endpoints:
    Actuator:
      Exposure:
        Include:
          - "*"
  Tracing:
    Exporter:
      Zipkin:
        Endpoint: http://localhost:9411/api/v2/spans
Consul:
  Host: localhost
  Port: 8500
  Discovery:
    Register: true
    HealthCheckPath: '/health'
Redis:
  Client:
    ConnectionString: localhost:6379,abortConnect=false,AllowAdmin=true
RabbitMq:
  Client:
    Uri: amqp://admin:secret@localhost:5672
Postgres:
  Client:
    ConnectionString: Host=127.0.0.1;Port=5432;Database=trace;Username=trace;Password=trace;Timeout=15;Pooling=true;MinPoolSize=1;MaxPoolSize=20;ConnectionLifeTime=15
Hangfire:
  Endpoint: '/schedule'
  Username: trace
  Password: trace
Minio:
  Secure: false
  Endpoint: minio:8080
  AccessKey: xxx-xxx-xxx
  SecretKey: xxx-xxx-xxx
ReverseProxy:
  Routes:
  Clusters:
    gateway:
      Destinations:
        main:
          Address: http://localhost:4570
